type: edu
files:
  - name: src/com/simonmoorecode/streamstutorial/domain/City.java
    visible: true
  - name: src/com/simonmoorecode/streamstutorial/domain/Student.java
    visible: true
  - name: src/com/simonmoorecode/streamstutorial/domain/Subject.java
    visible: true
  - name: src/com/simonmoorecode/streamstutorial/LoadStudents.java
    visible: true
  - name: src/com/simonmoorecode/streamstutorial/CountStudentsByCity.java
    visible: true
    placeholders:
      - offset: 375
        length: 97
        placeholder_text: return new HashMap<>();
  - name: test/com/simonmoorecode/streamstutorial/TestCountStudentsByCity.java
    visible: false
  - name: src/main/resources/students.csv
    visible: true
