type: edu
files:
  - name: src/com/simonmoorecode/streamstutorial/domain/City.java
    visible: true
  - name: src/com/simonmoorecode/streamstutorial/domain/Student.java
    visible: true
  - name: src/com/simonmoorecode/streamstutorial/domain/Subject.java
    visible: true
  - name: src/com/simonmoorecode/streamstutorial/LoadStudents.java
    visible: true
  - name: src/com/simonmoorecode/streamstutorial/GetDistinctListOfSubjects.java
    visible: true
    placeholders:
      - offset: 384
        length: 298
        placeholder_text: return new LinkedList<>();
  - name: test/com/simonmoorecode/streamstutorial/TestGetDistinctListOfSubjects.java
    visible: false
  - name: src/main/resources/students.csv
    visible: true
