content:
  - Calculate Average Grade
  - Counts Students By City
  - Filter Students By Grade
  - Find Min Student Age
  - Get Distinct List Of Subjects
  - Get Student Names
  - Group Students By City
